### ISSUE TITLE
Slogger 

### ISSUE THREAD

**Issue by mrjcleaver** [kitykity/dotw#1]
Hi! In case you don't know: you might like https://github.com/ttscoff/Slogger - it does a whole bunch of stuff for Day One.

Regards, M.

**Comment by kitykity** [comment]
Hi Martin,

Thank you for the tip! My little tools were more for historical posts--I
think Slogger is more for as-you-post, though I could be wrong :)

Have a great week!

Susan

On Fri, Feb 6, 2015 at 11:20 PM, Martin Cleaver notifications@github.com
wrote:

> Hi! In case you don't know: you might like
> https://github.com/ttscoff/Slogger - it does a whole bunch of stuff for
> Day One.
> 
> Regards, M.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kitykity/dotw/issues/1.

## 

Susan Pitman
about.me/susan.a.pitman
[image: Susan Pitman on about.me]
  http://about.me/susan.a.pitman
