### ISSUE TITLE
Dir structure?

### ISSUE THREAD

**Issue by chrisboden** [kitykity/dotw#2]
Hi, the processing of the archive seems to have gone fine but not sure how to now get these refecting in the actual Day One app.

Post processing, I now have thousands of files in home > dotw > dotwPosts eg done.post.000194

I tried manually copying some of these files to the Dropbox > Day One > Journal.dayone > entries folder to see if they would reflect in the Day One app timeline but knew that was a long shot.

Please let me know what the step after archive processing is in order to get the done.post.xyz files into the journal.

Thanks

**Comment by kitykity** [comment]
Hi Chris,

If the files in there say "done.", then they should be done--i.e. those are the files that should have been pulled into DayOne. (it tags them with done. when it's done with them.)

If you're positive they haven't, there must have been some other error messages while running the script...?

I'm going to be out of pocket for a few days, but I will try to get back to you in about a week if we can get some more info together...

Thanks :)
Susan

**Comment by chrisboden** [comment]
I think I see the issue:

"./dotw.bash: line 65: /usr/local/bin/dayone: No such file or directory"

I guess the script assumes the user is running dayone mac app. I'm actually using the mobile app synced to dropbox, which places the *.doentry journal entries in the Dropbox/Apps/Day One/Journal.dayone/entries

The dotw done.\* files seem to be in json rather than markdown so I assume just changing the bash script's path to the dayone app dir in dropbox will not help?

**Comment by kitykity** [comment]
Should be corrected with day one version 2.
